cc_binary(
    name="abstractfactory_ex",
    srcs=["main.cpp"],
    deps=[":abstractfactory_lib"],
)

cc_library(
    name="abstractfactory_lib",
    srcs=["abstractfactory_lib.cpp"],
    hdrs=["abstractfactory.hpp"],
    visibility=["//visibility:public"],
)